name: Slack Notification

on:
  push: {}
  pull_request: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get event details
        run: |
          event_type=${{ github.event_name }}
          if [[ ${event_type} == "push" ]]; then
            commit_url="${{ github.event.head_commit.url }}"
          else
            commit_url="${{ github.event.pull_request.html_url }}"
          fi
          message="
          {
            \"text\": \"GitHub Action build result: ${{ job.status }}\n${commit_url}\",
            \"blocks\": [
              {
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \"GitHub Action build result: ${{ job.status }}\n${commit_url}\"
                }
              }
            ]
          }"
          echo "::set-output name=message::$message"

      - name: Send message to Slack
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d "${{ steps.get-event-details.outputs.message }}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
